language: php

branches:
  except:
    - /^release-\d+\.\d+\.\d+.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - laminas-mkdoc-theme

env:
  global:
    - TESTS_LAMINAS_AUTH_ADAPTER_DBTABLE_PDO_SQLITE_ENABLED=true
    - SITE_URL: https://docs.laminas.dev/laminas-authentication
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/laminas/laminas-authentication.git
    - secure: "EkN2Vnzdt2UUN740UtTsM5PlaminasEBIBPN4fhgjc0kFYGSVKPB/bvsKAMgMKLl7Q1+YrcncpjfuiXuPlhKQhe2zgNGMncBfcOKePgxVstuzHed19ssQK5g67gTChNcqI679RKaSpN1CQwf5y0bZ8qHEPtv3JBuBJT9osPqNlLUQ37kQPC8417EYfmiLi1JL04rHsvitX1rRYZgGV53vFtCdpvy4/w/Iy5NU1KkoiiwueMtR80SL15qRmFYBgBxi5jrW/IpwDCDT+SOX2ZaPHq6Jv4Qb8ndyFoswIJD0PBpB98QpyG+5t7ciTmZGO7xW+aLmpE4Ci38OMkzeoCXzyOLL6Li8+VstjUD2atJ0uNyl60benchapOZoHVT7Nm51fUaXAzjR+Q6XalF1lyExgeEZ56yM6NHBVwOWl+8Rly4xhP4v3u4vCwHQ/R6dZbAhcPkr3CgFr4ra31kDTfJHnVKlhDnNz3jtn/kBofmtMdRAknVLhTlTwAc2K4ZBgXMPz7bJvMDiCDh695vqChREKcsciH2B6Ad8q3C/mV/ior8errFLaminasupRvvP3fEXEgei0YSrigh1mzvFjLaminasYMMs52EkZ6qd8YtBRJLJxfBNAIatp/RW+urpPA7JtSdyff1fesyZQBAqbJhMfUXwYsj6OuQPjAZ6yB/6D9TjCufG+Mha/y+wo="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - EXECUTE_CS_CHECK=true
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 7
    - php: hhvm 
  allow_failures:
    - php: hhvm

notifications:
  email: false

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/laminas/laminas-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./laminas-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi
